#%RAML 1.0
title: Traacs API
version: '1.0'
protocols:
  - HTTP
baseUri: 'http://localhost:9097/etrcs/{version}'

/processInvoice:
  post:
    description: Process an invoice
    body:
      application/json:
       
    responses:
      200:
        body:
          application/json:
          

/processRoeCapture:
  
  post: 
    description: Process ROE Capture
    body: 
      application/json:   
        
    responses: 
      200:
        body: 
          application/json: 

/invoiceRequest:
  
  post: 
    description: Invoice Request
    body: 
      application/json:   
        
    responses: 
      200:
        body: 
          application/json:
