package com.ebreez.etrcs.traacs.vo;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonAutoDetect(
	    fieldVisibility = JsonAutoDetect.Visibility.ANY,
	    getterVisibility = JsonAutoDetect.Visibility.NONE,
	    setterVisibility = JsonAutoDetect.Visibility.NONE
	)
@JsonInclude(Include.ALWAYS)
public class RoomDetailsJson implements Serializable {
	
	/** *  */
	private static final long serialVersionUID = 1L;
	
	@JsonProperty("STR_CHECK_IN_DATE")
	private String STR_CHECK_IN_DATE;
	
	@JsonProperty("STR_CHECK_OUT_DATE")
	private String STR_CHECK_OUT_DATE;
	
	@JsonProperty("INT_NO_OF_ROOMS")
	private Integer INT_NO_OF_ROOMS;
	
	@JsonProperty("INT_NO_OF_NIGHTS")
	private Integer INT_NO_OF_NIGHTS;
	
	@JsonProperty("STR_MEALS_PLAN")
	private String STR_MEALS_PLAN;
	
	@JsonProperty("STR_TRAVELER_ID")
	private String STR_TRAVELER_ID;
	
	@JsonProperty("STR_GUESTS")
	private String STR_GUESTS;
	
	@JsonProperty("STR_ADDITIONAL_GUESTS")
	private String STR_ADDITIONAL_GUESTS;
	
	@JsonProperty("STR_ROOM_TYPE")
	private String STR_ROOM_TYPE;
	
	@JsonProperty("INT_ADULT")
	private Integer INT_ADULT;
	
	@JsonProperty("INT_CHILD")
	private Integer INT_CHILD;
	
	@JsonProperty("DBL_PURCHASE_CUR_RATE_PER_NIGHT")
	private Double DBL_PURCHASE_CUR_RATE_PER_NIGHT;
	
	@JsonProperty("DBL_BASE_CUR_RATE_PER_NIGHT")
	private Double DBL_BASE_CUR_RATE_PER_NIGHT;
	
	@JsonProperty("DBL_SELLING_CUR_RATE_PER_NIGHT")
	private Double DBL_SELLING_CUR_RATE_PER_NIGHT;
	
	@JsonProperty("DBL_PURCHASE_CUR_TAX_PER_NIGHT")
	private Double DBL_PURCHASE_CUR_TAX_PER_NIGHT;

	@JsonProperty("DBL_BASE_CUR_TAX_PER_NIGHT")
	private Double DBL_BASE_CUR_TAX_PER_NIGHT;

	@JsonProperty("DBL_SELLING_CUR_TAX_PER_NIGHT")
	private Double DBL_SELLING_CUR_TAX_PER_NIGHT;
	
	@JsonProperty("DBL_PURCHASE_CUR_SUP_COMMISION")
	private Double DBL_PURCHASE_CUR_SUP_COMMISION;

	@JsonProperty("DBL_BASE_CUR_SUP_COMMISION")
	private Double DBL_BASE_CUR_SUP_COMMISION;

	@JsonProperty("DBL_SELLING_CUR_SUP_COMMISION")
	private Double DBL_SELLING_CUR_SUP_COMMISION;

	@JsonProperty("DBL_PURCHASE_CUR_SUPPLIER_AMOUNT")
	private Double DBL_PURCHASE_CUR_SUPPLIER_AMOUNT;
	
	@JsonProperty("DBL_BASE_CUR_SUPPLIER_AMOUNT")
	private Double DBL_BASE_CUR_SUPPLIER_AMOUNT;
	
	@JsonProperty("DBL_SELLING_CUR_SUPPLIER_AMOUNT")
	private Double DBL_SELLING_CUR_SUPPLIER_AMOUNT;
	
	@JsonProperty("DBL_PURCHASE_CUR_SERVICE_FEE")
	private Double DBL_PURCHASE_CUR_SERVICE_FEE;
	
	@JsonProperty("DBL_BASE_CUR_SERVICE_FEE")
	private Double DBL_BASE_CUR_SERVICE_FEE;
	
	@JsonProperty("DBL_SELLING_CUR_SERVICE_FEE")
	private Double DBL_SELLING_CUR_SERVICE_FEE;
	
	@JsonProperty("DBL_PURCHASE_CUR_EXTRA_EARNING")
	private Double DBL_PURCHASE_CUR_EXTRA_EARNING;
	
	@JsonProperty("DBL_BASE_CUR_EXTRA_EARNING")
	private Double DBL_BASE_CUR_EXTRA_EARNING;
	
	@JsonProperty("DBL_SELLING_CUR_EXTRA_EARNING")
	private Double DBL_SELLING_CUR_EXTRA_EARNING;
	
	@JsonProperty("DBL_PURCHASE_CUR_PAYBACK_AMOUNT")
	private Double DBL_PURCHASE_CUR_PAYBACK_AMOUNT;
	
	@JsonProperty("DBL_BASE_CUR_PAYBACK_AMOUNT")
	private Double DBL_BASE_CUR_PAYBACK_AMOUNT;
	
	@JsonProperty("DBL_SELLING_CUR_PAYBACK_AMOUNT")
	private Double DBL_SELLING_CUR_PAYBACK_AMOUNT;
	
	@JsonProperty("DBL_PURCHASE_CUR_CC_CHARGES")
	private Double DBL_PURCHASE_CUR_CC_CHARGES;
	
	@JsonProperty("DBL_BASE_CUR_CC_CHARGES")
	private Double DBL_BASE_CUR_CC_CHARGES;
	
	@JsonProperty("DBL_SELLING_CUR_CC_CHARGES")
	private Double DBL_SELLING_CUR_CC_CHARGES;

	@JsonProperty("DBL_PURCHASE_CUR_DISCOUNT")
	private Double DBL_PURCHASE_CUR_DISCOUNT;
	
	@JsonProperty("DBL_BASE_CUR_DISCOUNT")
	private Double DBL_BASE_CUR_DISCOUNT;
	
	@JsonProperty("DBL_SELLING_CUR_DISCOUNT")
	private Double DBL_SELLING_CUR_DISCOUNT;

	@JsonProperty("DBL_PURCHASE_CUR_PRICE")
	private Double DBL_PURCHASE_CUR_PRICE;
	
	@JsonProperty("DBL_BASE_CUR_PRICE")
	private Double DBL_BASE_CUR_PRICE;
	
	@JsonProperty("DBL_SELLING_CUR_PRICE")
	private Double DBL_SELLING_CUR_PRICE;
	
	@JsonProperty("DBL_PURCHASE_CUR_INPUT_VAT") 
	private Double DBL_PURCHASE_CUR_INPUT_VAT;
	
	@JsonProperty("DBL_BASE_CUR_INPUT_VAT") 
	private Double DBL_BASE_CUR_INPUT_VAT;
	
	@JsonProperty("DBL_SELLING_CUR_INPUT_VAT") 
	private Double DBL_SELLING_CUR_INPUT_VAT;
	
	@JsonProperty("DBL_PURCHASE_CUR_OUTPUT_VAT") 
	private Double DBL_PURCHASE_CUR_OUTPUT_VAT;
	
	@JsonProperty("DBL_BASE_CUR_OUTPUT_VAT") 
	private Double DBL_BASE_CUR_OUTPUT_VAT;
	
	@JsonProperty("DBL_SELLING_CUR_OUTPUT_VAT") 
	private Double DBL_SELLING_CUR_OUTPUT_VAT;
	

	public String getSTR_CHECK_IN_DATE() {
		return STR_CHECK_IN_DATE;
	}

	public void setSTR_CHECK_IN_DATE(String sTR_CHECK_IN_DATE) {
		STR_CHECK_IN_DATE = sTR_CHECK_IN_DATE;
	}

	public String getSTR_CHECK_OUT_DATE() {
		return STR_CHECK_OUT_DATE;
	}

	public void setSTR_CHECK_OUT_DATE(String sTR_CHECK_OUT_DATE) {
		STR_CHECK_OUT_DATE = sTR_CHECK_OUT_DATE;
	}

	public Integer getINT_NO_OF_ROOMS() {
		return INT_NO_OF_ROOMS;
	}

	public void setINT_NO_OF_ROOMS(Integer iNT_NO_OF_ROOMS) {
		INT_NO_OF_ROOMS = iNT_NO_OF_ROOMS;
	}

	public Integer getINT_NO_OF_NIGHTS() {
		return INT_NO_OF_NIGHTS;
	}

	public void setINT_NO_OF_NIGHTS(Integer iNT_NO_OF_NIGHTS) {
		INT_NO_OF_NIGHTS = iNT_NO_OF_NIGHTS;
	}

	public String getSTR_MEALS_PLAN() {
		return STR_MEALS_PLAN;
	}

	public void setSTR_MEALS_PLAN(String sTR_MEALS_PLAN) {
		STR_MEALS_PLAN = sTR_MEALS_PLAN;
	}

	public String getSTR_TRAVELER_ID() {
		return STR_TRAVELER_ID;
	}

	public void setSTR_TRAVELER_ID(String sTR_TRAVELER_ID) {
		STR_TRAVELER_ID = sTR_TRAVELER_ID;
	}

	public String getSTR_GUESTS() {
		return STR_GUESTS;
	}

	public void setSTR_GUESTS(String sTR_GUESTS) {
		STR_GUESTS = sTR_GUESTS;
	}

	public String getSTR_ADDITIONAL_GUESTS() {
		return STR_ADDITIONAL_GUESTS;
	}

	public void setSTR_ADDITIONAL_GUESTS(String sTR_ADDITIONAL_GUESTS) {
		STR_ADDITIONAL_GUESTS = sTR_ADDITIONAL_GUESTS;
	}

	public String getSTR_ROOM_TYPE() {
		return STR_ROOM_TYPE;
	}

	public void setSTR_ROOM_TYPE(String sTR_ROOM_TYPE) {
		STR_ROOM_TYPE = sTR_ROOM_TYPE;
	}

	public Integer getINT_ADULT() {
		return INT_ADULT;
	}

	public void setINT_ADULT(Integer iNT_ADULT) {
		INT_ADULT = iNT_ADULT;
	}

	public Integer getINT_CHILD() {
		return INT_CHILD;
	}

	public void setINT_CHILD(Integer iNT_CHILD) {
		INT_CHILD = iNT_CHILD;
	}

	public Double getDBL_PURCHASE_CUR_RATE_PER_NIGHT() {
		return DBL_PURCHASE_CUR_RATE_PER_NIGHT;
	}

	public void setDBL_PURCHASE_CUR_RATE_PER_NIGHT(Double dBL_PURCHASE_CUR_RATE_PER_NIGHT) {
		DBL_PURCHASE_CUR_RATE_PER_NIGHT = dBL_PURCHASE_CUR_RATE_PER_NIGHT;
	}

	public Double getDBL_BASE_CUR_RATE_PER_NIGHT() {
		return DBL_BASE_CUR_RATE_PER_NIGHT;
	}

	public void setDBL_BASE_CUR_RATE_PER_NIGHT(Double dBL_BASE_CUR_RATE_PER_NIGHT) {
		DBL_BASE_CUR_RATE_PER_NIGHT = dBL_BASE_CUR_RATE_PER_NIGHT;
	}

	public Double getDBL_SELLING_CUR_RATE_PER_NIGHT() {
		return DBL_SELLING_CUR_RATE_PER_NIGHT;
	}

	public void setDBL_SELLING_CUR_RATE_PER_NIGHT(Double dBL_SELLING_CUR_RATE_PER_NIGHT) {
		DBL_SELLING_CUR_RATE_PER_NIGHT = dBL_SELLING_CUR_RATE_PER_NIGHT;
	}

	public Double getDBL_PURCHASE_CUR_TAX_PER_NIGHT() {
		return DBL_PURCHASE_CUR_TAX_PER_NIGHT;
	}

	public void setDBL_PURCHASE_CUR_TAX_PER_NIGHT(Double dBL_PURCHASE_CUR_TAX_PER_NIGHT) {
		DBL_PURCHASE_CUR_TAX_PER_NIGHT = dBL_PURCHASE_CUR_TAX_PER_NIGHT;
	}

	public Double getDBL_BASE_CUR_TAX_PER_NIGHT() {
		return DBL_BASE_CUR_TAX_PER_NIGHT;
	}

	public void setDBL_BASE_CUR_TAX_PER_NIGHT(Double dBL_BASE_CUR_TAX_PER_NIGHT) {
		DBL_BASE_CUR_TAX_PER_NIGHT = dBL_BASE_CUR_TAX_PER_NIGHT;
	}

	public Double getDBL_SELLING_CUR_TAX_PER_NIGHT() {
		return DBL_SELLING_CUR_TAX_PER_NIGHT;
	}

	public void setDBL_SELLING_CUR_TAX_PER_NIGHT(Double dBL_SELLING_CUR_TAX_PER_NIGHT) {
		DBL_SELLING_CUR_TAX_PER_NIGHT = dBL_SELLING_CUR_TAX_PER_NIGHT;
	}

	public Double getDBL_PURCHASE_CUR_SUP_COMMISION() {
		return DBL_PURCHASE_CUR_SUP_COMMISION;
	}

	public void setDBL_PURCHASE_CUR_SUP_COMMISION(Double dBL_PURCHASE_CUR_SUP_COMMISION) {
		DBL_PURCHASE_CUR_SUP_COMMISION = dBL_PURCHASE_CUR_SUP_COMMISION;
	}

	public Double getDBL_BASE_CUR_SUP_COMMISION() {
		return DBL_BASE_CUR_SUP_COMMISION;
	}

	public void setDBL_BASE_CUR_SUP_COMMISION(Double dBL_BASE_CUR_SUP_COMMISION) {
		DBL_BASE_CUR_SUP_COMMISION = dBL_BASE_CUR_SUP_COMMISION;
	}

	public Double getDBL_SELLING_CUR_SUP_COMMISION() {
		return DBL_SELLING_CUR_SUP_COMMISION;
	}

	public void setDBL_SELLING_CUR_SUP_COMMISION(Double dBL_SELLING_CUR_SUP_COMMISION) {
		DBL_SELLING_CUR_SUP_COMMISION = dBL_SELLING_CUR_SUP_COMMISION;
	}

	public Double getDBL_PURCHASE_CUR_SUPPLIER_AMOUNT() {
		return DBL_PURCHASE_CUR_SUPPLIER_AMOUNT;
	}

	public void setDBL_PURCHASE_CUR_SUPPLIER_AMOUNT(Double dBL_PURCHASE_CUR_SUPPLIER_AMOUNT) {
		DBL_PURCHASE_CUR_SUPPLIER_AMOUNT = dBL_PURCHASE_CUR_SUPPLIER_AMOUNT;
	}

	public Double getDBL_BASE_CUR_SUPPLIER_AMOUNT() {
		return DBL_BASE_CUR_SUPPLIER_AMOUNT;
	}

	public void setDBL_BASE_CUR_SUPPLIER_AMOUNT(Double dBL_BASE_CUR_SUPPLIER_AMOUNT) {
		DBL_BASE_CUR_SUPPLIER_AMOUNT = dBL_BASE_CUR_SUPPLIER_AMOUNT;
	}

	public Double getDBL_SELLING_CUR_SUPPLIER_AMOUNT() {
		return DBL_SELLING_CUR_SUPPLIER_AMOUNT;
	}

	public void setDBL_SELLING_CUR_SUPPLIER_AMOUNT(Double dBL_SELLING_CUR_SUPPLIER_AMOUNT) {
		DBL_SELLING_CUR_SUPPLIER_AMOUNT = dBL_SELLING_CUR_SUPPLIER_AMOUNT;
	}

	public Double getDBL_PURCHASE_CUR_SERVICE_FEE() {
		return DBL_PURCHASE_CUR_SERVICE_FEE;
	}

	public void setDBL_PURCHASE_CUR_SERVICE_FEE(Double dBL_PURCHASE_CUR_SERVICE_FEE) {
		DBL_PURCHASE_CUR_SERVICE_FEE = dBL_PURCHASE_CUR_SERVICE_FEE;
	}

	public Double getDBL_BASE_CUR_SERVICE_FEE() {
		return DBL_BASE_CUR_SERVICE_FEE;
	}

	public void setDBL_BASE_CUR_SERVICE_FEE(Double dBL_BASE_CUR_SERVICE_FEE) {
		DBL_BASE_CUR_SERVICE_FEE = dBL_BASE_CUR_SERVICE_FEE;
	}

	public Double getDBL_SELLING_CUR_SERVICE_FEE() {
		return DBL_SELLING_CUR_SERVICE_FEE;
	}

	public void setDBL_SELLING_CUR_SERVICE_FEE(Double dBL_SELLING_CUR_SERVICE_FEE) {
		DBL_SELLING_CUR_SERVICE_FEE = dBL_SELLING_CUR_SERVICE_FEE;
	}

	public Double getDBL_PURCHASE_CUR_EXTRA_EARNING() {
		return DBL_PURCHASE_CUR_EXTRA_EARNING;
	}

	public void setDBL_PURCHASE_CUR_EXTRA_EARNING(Double dBL_PURCHASE_CUR_EXTRA_EARNING) {
		DBL_PURCHASE_CUR_EXTRA_EARNING = dBL_PURCHASE_CUR_EXTRA_EARNING;
	}

	public Double getDBL_BASE_CUR_EXTRA_EARNING() {
		return DBL_BASE_CUR_EXTRA_EARNING;
	}

	public void setDBL_BASE_CUR_EXTRA_EARNING(Double dBL_BASE_CUR_EXTRA_EARNING) {
		DBL_BASE_CUR_EXTRA_EARNING = dBL_BASE_CUR_EXTRA_EARNING;
	}

	public Double getDBL_SELLING_CUR_EXTRA_EARNING() {
		return DBL_SELLING_CUR_EXTRA_EARNING;
	}

	public void setDBL_SELLING_CUR_EXTRA_EARNING(Double dBL_SELLING_CUR_EXTRA_EARNING) {
		DBL_SELLING_CUR_EXTRA_EARNING = dBL_SELLING_CUR_EXTRA_EARNING;
	}

	public Double getDBL_PURCHASE_CUR_PAYBACK_AMOUNT() {
		return DBL_PURCHASE_CUR_PAYBACK_AMOUNT;
	}

	public void setDBL_PURCHASE_CUR_PAYBACK_AMOUNT(Double dBL_PURCHASE_CUR_PAYBACK_AMOUNT) {
		DBL_PURCHASE_CUR_PAYBACK_AMOUNT = dBL_PURCHASE_CUR_PAYBACK_AMOUNT;
	}

	public Double getDBL_BASE_CUR_PAYBACK_AMOUNT() {
		return DBL_BASE_CUR_PAYBACK_AMOUNT;
	}

	public void setDBL_BASE_CUR_PAYBACK_AMOUNT(Double dBL_BASE_CUR_PAYBACK_AMOUNT) {
		DBL_BASE_CUR_PAYBACK_AMOUNT = dBL_BASE_CUR_PAYBACK_AMOUNT;
	}

	public Double getDBL_SELLING_CUR_PAYBACK_AMOUNT() {
		return DBL_SELLING_CUR_PAYBACK_AMOUNT;
	}

	public void setDBL_SELLING_CUR_PAYBACK_AMOUNT(Double dBL_SELLING_CUR_PAYBACK_AMOUNT) {
		DBL_SELLING_CUR_PAYBACK_AMOUNT = dBL_SELLING_CUR_PAYBACK_AMOUNT;
	}

	public Double getDBL_PURCHASE_CUR_CC_CHARGES() {
		return DBL_PURCHASE_CUR_CC_CHARGES;
	}

	public void setDBL_PURCHASE_CUR_CC_CHARGES(Double dBL_PURCHASE_CUR_CC_CHARGES) {
		DBL_PURCHASE_CUR_CC_CHARGES = dBL_PURCHASE_CUR_CC_CHARGES;
	}

	public Double getDBL_BASE_CUR_CC_CHARGES() {
		return DBL_BASE_CUR_CC_CHARGES;
	}

	public void setDBL_BASE_CUR_CC_CHARGES(Double dBL_BASE_CUR_CC_CHARGES) {
		DBL_BASE_CUR_CC_CHARGES = dBL_BASE_CUR_CC_CHARGES;
	}

	public Double getDBL_SELLING_CUR_CC_CHARGES() {
		return DBL_SELLING_CUR_CC_CHARGES;
	}

	public void setDBL_SELLING_CUR_CC_CHARGES(Double dBL_SELLING_CUR_CC_CHARGES) {
		DBL_SELLING_CUR_CC_CHARGES = dBL_SELLING_CUR_CC_CHARGES;
	}

	public Double getDBL_PURCHASE_CUR_DISCOUNT() {
		return DBL_PURCHASE_CUR_DISCOUNT;
	}

	public void setDBL_PURCHASE_CUR_DISCOUNT(Double dBL_PURCHASE_CUR_DISCOUNT) {
		DBL_PURCHASE_CUR_DISCOUNT = dBL_PURCHASE_CUR_DISCOUNT;
	}

	public Double getDBL_BASE_CUR_DISCOUNT() {
		return DBL_BASE_CUR_DISCOUNT;
	}

	public void setDBL_BASE_CUR_DISCOUNT(Double dBL_BASE_CUR_DISCOUNT) {
		DBL_BASE_CUR_DISCOUNT = dBL_BASE_CUR_DISCOUNT;
	}

	public Double getDBL_SELLING_CUR_DISCOUNT() {
		return DBL_SELLING_CUR_DISCOUNT;
	}

	public void setDBL_SELLING_CUR_DISCOUNT(Double dBL_SELLING_CUR_DISCOUNT) {
		DBL_SELLING_CUR_DISCOUNT = dBL_SELLING_CUR_DISCOUNT;
	}

	public Double getDBL_PURCHASE_CUR_PRICE() {
		return DBL_PURCHASE_CUR_PRICE;
	}

	public void setDBL_PURCHASE_CUR_PRICE(Double dBL_PURCHASE_CUR_PRICE) {
		DBL_PURCHASE_CUR_PRICE = dBL_PURCHASE_CUR_PRICE;
	}

	public Double getDBL_BASE_CUR_PRICE() {
		return DBL_BASE_CUR_PRICE;
	}

	public void setDBL_BASE_CUR_PRICE(Double dBL_BASE_CUR_PRICE) {
		DBL_BASE_CUR_PRICE = dBL_BASE_CUR_PRICE;
	}

	public Double getDBL_SELLING_CUR_PRICE() {
		return DBL_SELLING_CUR_PRICE;
	}

	public void setDBL_SELLING_CUR_PRICE(Double dBL_SELLING_CUR_PRICE) {
		DBL_SELLING_CUR_PRICE = dBL_SELLING_CUR_PRICE;
	}

	public Double getDBL_PURCHASE_CUR_INPUT_VAT() {
		return DBL_PURCHASE_CUR_INPUT_VAT;
	}

	public void setDBL_PURCHASE_CUR_INPUT_VAT(Double dBL_PURCHASE_CUR_INPUT_VAT) {
		DBL_PURCHASE_CUR_INPUT_VAT = dBL_PURCHASE_CUR_INPUT_VAT;
	}

	public Double getDBL_BASE_CUR_INPUT_VAT() {
		return DBL_BASE_CUR_INPUT_VAT;
	}

	public void setDBL_BASE_CUR_INPUT_VAT(Double dBL_BASE_CUR_INPUT_VAT) {
		DBL_BASE_CUR_INPUT_VAT = dBL_BASE_CUR_INPUT_VAT;
	}

	public Double getDBL_SELLING_CUR_INPUT_VAT() {
		return DBL_SELLING_CUR_INPUT_VAT;
	}

	public void setDBL_SELLING_CUR_INPUT_VAT(Double dBL_SELLING_CUR_INPUT_VAT) {
		DBL_SELLING_CUR_INPUT_VAT = dBL_SELLING_CUR_INPUT_VAT;
	}

	public Double getDBL_PURCHASE_CUR_OUTPUT_VAT() {
		return DBL_PURCHASE_CUR_OUTPUT_VAT;
	}

	public void setDBL_PURCHASE_CUR_OUTPUT_VAT(Double dBL_PURCHASE_CUR_OUTPUT_VAT) {
		DBL_PURCHASE_CUR_OUTPUT_VAT = dBL_PURCHASE_CUR_OUTPUT_VAT;
	}

	public Double getDBL_BASE_CUR_OUTPUT_VAT() {
		return DBL_BASE_CUR_OUTPUT_VAT;
	}

	public void setDBL_BASE_CUR_OUTPUT_VAT(Double dBL_BASE_CUR_OUTPUT_VAT) {
		DBL_BASE_CUR_OUTPUT_VAT = dBL_BASE_CUR_OUTPUT_VAT;
	}

	public Double getDBL_SELLING_CUR_OUTPUT_VAT() {
		return DBL_SELLING_CUR_OUTPUT_VAT;
	}

	public void setDBL_SELLING_CUR_OUTPUT_VAT(Double dBL_SELLING_CUR_OUTPUT_VAT) {
		DBL_SELLING_CUR_OUTPUT_VAT = dBL_SELLING_CUR_OUTPUT_VAT;
	}

}
