package com.ebreez.etrcs.traacs.vo;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;


@JsonAutoDetect(
	    fieldVisibility = JsonAutoDetect.Visibility.ANY,
	    getterVisibility = JsonAutoDetect.Visibility.NONE,
	    setterVisibility = JsonAutoDetect.Visibility.NONE
	)
@JsonInclude(Include.ALWAYS)
public class TicketJsonMaster implements Serializable {
	
	/** *  */
	private static final long serialVersionUID = 1L;

	@JsonProperty("STR_TYPE")
	private String STR_TYPE;
	
	@JsonProperty("STR_AIRLINE_REF_NO")
	private String STR_AIRLINE_REF_NO;
	
	@JsonProperty("STR_XO_NUMBER")
	private String STR_XO_NUMBER;
	
	@JsonProperty("STR_TICKET_NO") 
	private String STR_TICKET_NO;
	
	@JsonProperty("STR_AIRLINE_CHARACTER_CODE") 
	private String STR_AIRLINE_CHARACTER_CODE;
	
	@JsonProperty("STR_AIRLINE_NUMERIC_CODE")
	private String STR_AIRLINE_NUMERIC_CODE;
	
	@JsonProperty("STR_AIRLINE_NAME")
	private String STR_AIRLINE_NAME;
	
	@JsonProperty("STR_SUPPLIER_CODE") 
	private String STR_SUPPLIER_CODE;
	
	@JsonProperty("STR_CORP_CREDIT_CARD_ACCOUNT_CODE")
	private String STR_CORP_CREDIT_CARD_ACCOUNT_CODE;
	
	@JsonProperty("STR_CUSTOMER_CORP_CREDIT_CARD_ACCOUNT_CODE")
	private String STR_CUSTOMER_CORP_CREDIT_CARD_ACCOUNT_CODE;
	
	@JsonProperty("STR_REFUND_DATE")
	private String STR_REFUND_DATE;
	
	@JsonProperty("STR_TICKET_ISSUE_DATE")
	private String STR_TICKET_ISSUE_DATE;
	
	@JsonProperty("STR_REPORTING_DATE")
	private String STR_REPORTING_DATE;
	
	@JsonProperty("STR_TICKET_TYPE") 
	private String STR_TICKET_TYPE;
	
	@JsonProperty("STR_TRAVELER_ID")
	private String STR_TRAVELER_ID;
	
	@JsonProperty("STR_PAX_NAME")
	private String STR_PAX_NAME;
	
	@JsonProperty("STR_ADDITIONAL_PAX") 
	private String STR_ADDITIONAL_PAX;
	
	@JsonProperty("STR_SECTOR")
	private String STR_SECTOR;

	@JsonProperty("CHR_TRAVELER_CLASS")
	private String CHR_TRAVELER_CLASS;
	
	@JsonProperty("CHR_RETURN_CLASS")
	private String CHR_RETURN_CLASS;
	
	@JsonProperty("STR_REGION_CODE")
	private String STR_REGION_CODE;
	
	@JsonProperty("STR_LPO_NO") 
	private String STR_LPO_NO;
	
	@JsonProperty("STR_REFUND_STAFF_CODE") 
	private String STR_REFUND_STAFF_CODE;
	
	@JsonProperty("STR_REFUND_STAFF_CHARACTER_CODE") 
	private String STR_REFUND_STAFF_CHARACTER_CODE;
	
	@JsonProperty("STR_REFUND_STAFF_EMAIL_ID") 
	private String STR_REFUND_STAFF_EMAIL_ID;
	
	@JsonProperty("STR_CUSTOMER_REF_NO")
	private String STR_CUSTOMER_REF_NO;
	
	@JsonProperty("STR_CUSTOMER_EMP_NO")
	private String STR_CUSTOMER_EMP_NO;
	
	@JsonProperty("STR_BOOKING_STAFF_CODE")
	private String STR_BOOKING_STAFF_CODE;
	
	@JsonProperty("STR_BOOKING_STAFF_CHARACTER_CODE")
	private String STR_BOOKING_STAFF_CHARACTER_CODE;
	
	@JsonProperty("STR_BOOKING_STAFF_EMAIL_ID")
	private String STR_BOOKING_STAFF_EMAIL_ID;
	
	@JsonProperty("STR_TICKETING_STAFF_CODE")
	private String STR_TICKETING_STAFF_CODE;
	
	@JsonProperty("STR_TICKETING_STAFF_CHARACTER_CODE")
	private String STR_TICKETING_STAFF_CHARACTER_CODE;
	
	@JsonProperty("STR_TICKETING_STAFF_EMAIL_ID")
	private String STR_TICKETING_STAFF_EMAIL_ID;
	
	@JsonProperty("STR_BOOKING_AGENCY_IATA_NO")
	private String STR_BOOKING_AGENCY_IATA_NO;
	
	@JsonProperty("STR_TICKETING_AGENCY_IATA_NO")
	private String STR_TICKETING_AGENCY_IATA_NO;
	
	@JsonProperty("STR_BOOKING_AGENCY_OFFICE_ID")
	private String STR_BOOKING_AGENCY_OFFICE_ID;
	
	@JsonProperty("STR_TICKETING_AGENCY_OFFICE_ID")
	private String STR_TICKETING_AGENCY_OFFICE_ID;
	
	@JsonProperty("STR_PNR_FIRST_OWNER_OFFICE_ID")
	private String STR_PNR_FIRST_OWNER_OFFICE_ID;
	
	@JsonProperty("STR_PNR_CURRENT_OWNER_OFFICE_ID") 
	private String STR_PNR_CURRENT_OWNER_OFFICE_ID;
	
	@JsonProperty("STR_GDS") 
	private String STR_GDS;
	
	@JsonProperty("STR_TOUR_CODE")
	private String STR_TOUR_CODE;
	
	@JsonProperty("STR_FARE_BASIS")
	private String STR_FARE_BASIS;
	
	@JsonProperty("STR_PNR_NO")
	private String STR_PNR_NO;
	
	@JsonProperty("STR_AIRLINE_PNR")
	private String STR_AIRLINE_PNR;
	
	@JsonProperty("INT_NO_OF_PAX") 
	private Integer INT_NO_OF_PAX;
	
	@JsonProperty("STR_PAX_TYPE")
	private String STR_PAX_TYPE;
	
	@JsonProperty("STR_LAST_CONJ_TICKET")
	private String STR_LAST_CONJ_TICKET;
	
	@JsonProperty("STR_ORIGINAL_ISSUE") 
	private String STR_ORIGINAL_ISSUE;
	
	@JsonProperty("STR_TRAVEL_DATE")
	private String STR_TRAVEL_DATE;
	
	@JsonProperty("STR_RETURN_DATE")
	private String STR_RETURN_DATE;
	
	@JsonProperty("STR_TICKET_REMARK")
	private String STR_TICKET_REMARK;
	
	@JsonProperty("STR_REFUND_STATUS")
	private String STR_REFUND_STATUS;
	
	@JsonProperty("STR_PRODUCT") 
	private String STR_PRODUCT;
	
	@JsonProperty("DBL_PURCHASE_ROE") 
	private Double DBL_PURCHASE_ROE;
	
	@JsonProperty("STR_PURCHASE_CUR_CODE") 
	private String STR_PURCHASE_CUR_CODE;
	
	@JsonProperty("DBL_PURCHASE_CUR_PUBLISHED_FARE") 
	private Double DBL_PURCHASE_CUR_PUBLISHED_FARE;
	
	@JsonProperty("DBL_BASE_CUR_PUBLISHED_FARE") 
	private Double DBL_BASE_CUR_PUBLISHED_FARE;
	
	@JsonProperty("DBL_SELLING_CUR_PUBLISHED_FARE") 
	private Double DBL_SELLING_CUR_PUBLISHED_FARE;
	
	@JsonProperty("DBL_PURCHASE_CUR_TOTAL_MARKET_FARE") 
	private Double DBL_PURCHASE_CUR_TOTAL_MARKET_FARE;
	
	@JsonProperty("DBL_BASE_CUR_TOTAL_MARKET_FARE") 
	private Double DBL_BASE_CUR_TOTAL_MARKET_FARE;
	
	@JsonProperty("DBL_SELLING_CUR_TOTAL_MARKET_FARE") 
	private Double DBL_SELLING_CUR_TOTAL_MARKET_FARE;
	
	@JsonProperty("DBL_PURCHASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD") 
	private Double DBL_PURCHASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD;
	
	@JsonProperty("DBL_BASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD") 
	private Double DBL_BASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD;
	
	@JsonProperty("DBL_SELLING_CUR_TOTAL_MARKET_FARE_CREDIT_CARD") 
	private Double DBL_SELLING_CUR_TOTAL_MARKET_FARE_CREDIT_CARD;
	
	@JsonProperty("STR_TAX_DETAILS") 
	private String STR_TAX_DETAILS;
	
	@JsonProperty("DBL_PURCHASE_CUR_TOTAL_TAX")
	private Double DBL_PURCHASE_CUR_TOTAL_TAX;
	
	@JsonProperty("DBL_BASE_CUR_TOTAL_TAX") 
	private Double DBL_BASE_CUR_TOTAL_TAX;
	
	@JsonProperty("DBL_SELLING_CUR_TOTAL_TAX") 
	private Double DBL_SELLING_CUR_TOTAL_TAX;
	
	@JsonProperty("DBL_PURCHASE_CUR_TOTAL_TAX_CREDIT_CARD") 
	private Double DBL_PURCHASE_CUR_TOTAL_TAX_CREDIT_CARD;
	
	@JsonProperty("DBL_BASE_CUR_TOTAL_TAX_CREDIT_CARD") 
	private Double DBL_BASE_CUR_TOTAL_TAX_CREDIT_CARD;
	
	@JsonProperty("DBL_SELLING_CUR_TOTAL_TAX_CREDIT_CARD") 
	private Double DBL_SELLING_CUR_TOTAL_TAX_CREDIT_CARD;
	
	@JsonProperty("DBL_PURCHASE_CUR_STD_COMMISION") 
	private Double DBL_PURCHASE_CUR_STD_COMMISION;
	
	@JsonProperty("DBL_BASE_CUR_STD_COMMISION") 
	private Double DBL_BASE_CUR_STD_COMMISION;
	
	@JsonProperty("DBL_SELLING_CUR_STD_COMMISION") 
	private Double DBL_SELLING_CUR_STD_COMMISION;
	
	@JsonProperty("DBL_PURCHASE_CUR_SUPPLIER_FEE") 
	private Double DBL_PURCHASE_CUR_SUPPLIER_FEE;
	
	@JsonProperty("DBL_BASE_CUR_SUPPLIER_FEE") 
	private Double DBL_BASE_CUR_SUPPLIER_FEE;
	
	@JsonProperty("DBL_SELLING_CUR_SUPPLIER_FEE") 
	private Double DBL_SELLING_CUR_SUPPLIER_FEE;
	
	@JsonProperty("DBL_PURCHASE_CUR_AIRLINE_CHARGE") 
	private Double DBL_PURCHASE_CUR_AIRLINE_CHARGE;
	
	@JsonProperty("DBL_BASE_CUR_AIRLINE_CHARGE") 
	private Double DBL_BASE_CUR_AIRLINE_CHARGE;
	
	@JsonProperty("DBL_SELLING_CUR_AIRLINE_CHARGE") 
	private Double DBL_SELLING_CUR_AIRLINE_CHARGE;
	
	@JsonProperty("DBL_PURCHASE_CUR_SUPPLIER_NET") 
	private Double DBL_PURCHASE_CUR_SUPPLIER_NET;
	
	@JsonProperty("DBL_BASE_CUR_SUPPLIER_NET") 
	private Double DBL_BASE_CUR_SUPPLIER_NET;
	
	@JsonProperty("DBL_SELLING_CUR_SUPPLIER_NET") 
	private Double DBL_SELLING_CUR_SUPPLIER_NET;
	
	@JsonProperty("DBL_PURCHASE_CUR_AGENCY_CHARGE") 
	private Double DBL_PURCHASE_CUR_AGENCY_CHARGE;
	
	@JsonProperty("DBL_BASE_CUR_AGENCY_CHARGE") 
	private Double DBL_BASE_CUR_AGENCY_CHARGE;
	
	@JsonProperty("DBL_SELLING_CUR_AGENCY_CHARGE") 
	private Double DBL_SELLING_CUR_AGENCY_CHARGE;
	
	@JsonProperty("DBL_PURCHASE_CUR_SUPPLIER_AMOUNT") 
	private Double DBL_PURCHASE_CUR_SUPPLIER_AMOUNT;
	
	@JsonProperty("DBL_BASE_CUR_SUPPLIER_AMOUNT") 
	private Double DBL_BASE_CUR_SUPPLIER_AMOUNT;
	
	@JsonProperty("DBL_SELLING_CUR_SUPPLIER_AMOUNT") 
	private Double DBL_SELLING_CUR_SUPPLIER_AMOUNT;
	
	@JsonProperty("DBL_PURCHASE_CUR_SERVICE_FEE") 
	private Double DBL_PURCHASE_CUR_SERVICE_FEE;
	
	@JsonProperty("DBL_BASE_CUR_SERVICE_FEE") 
	private Double DBL_BASE_CUR_SERVICE_FEE;
	
	@JsonProperty("DBL_SELLING_CUR_SERVICE_FEE") 
	private Double DBL_SELLING_CUR_SERVICE_FEE;
	
	@JsonProperty("DBL_PURCHASE_CUR_EXTRA_EARNING") 
	private Double DBL_PURCHASE_CUR_EXTRA_EARNING;
	
	@JsonProperty("DBL_BASE_CUR_EXTRA_EARNING") 
	private Double DBL_BASE_CUR_EXTRA_EARNING;
	
	@JsonProperty("DBL_SELLING_CUR_EXTRA_EARNING") 
	private Double DBL_SELLING_CUR_EXTRA_EARNING;
	
	@JsonProperty("DBL_PURCHASE_CUR_PAYBACK_AMOUNT") 
	private Double DBL_PURCHASE_CUR_PAYBACK_AMOUNT;
	
	@JsonProperty("DBL_BASE_CUR_PAYBACK_AMOUNT") 
	private Double DBL_BASE_CUR_PAYBACK_AMOUNT;	
	
	@JsonProperty("DBL_SELLING_CUR_PAYBACK_AMOUNT") 
	private Double DBL_SELLING_CUR_PAYBACK_AMOUNT;
	
	@JsonProperty("STR_PAYBACK_ACCOUNT_CODE") 
	private String STR_PAYBACK_ACCOUNT_CODE;
	
	@JsonProperty("DBL_PURCHASE_CUR_CREDIT_CARD_CHARGES") 
	private Double DBL_PURCHASE_CUR_CREDIT_CARD_CHARGES;
	
	@JsonProperty("DBL_BASE_CUR_CREDIT_CARD_CHARGES") 
	private Double DBL_BASE_CUR_CREDIT_CARD_CHARGES;
	
	@JsonProperty("DBL_SELLING_CUR_CREDIT_CARD_CHARGES") 
	private Double DBL_SELLING_CUR_CREDIT_CARD_CHARGES;
	
	@JsonProperty("DBL_PURCHASE_CUR_DISCOUNT") 
	private Double DBL_PURCHASE_CUR_DISCOUNT;
	
	@JsonProperty("DBL_BASE_CUR_DISCOUNT") 
	private Double DBL_BASE_CUR_DISCOUNT;
	
	@JsonProperty("DBL_SELLING_CUR_DISCOUNT") 
	private Double DBL_SELLING_CUR_DISCOUNT;
	
	@JsonProperty("DBL_PURCHASE_CUR_PRICE") 
	private Double DBL_PURCHASE_CUR_PRICE;
	
	@JsonProperty("DBL_BASE_CUR_PRICE") 
	private Double DBL_BASE_CUR_PRICE;
	
	@JsonProperty("DBL_SELLING_CUR_PRICE") 
	private Double DBL_SELLING_CUR_PRICE;
	
	@JsonProperty("DBL_PURCHASE_CUR_CLIENT_NET") 
	private Double DBL_PURCHASE_CUR_CLIENT_NET;
	
	@JsonProperty("DBL_BASE_CUR_CLIENT_NET") 
	private Double DBL_BASE_CUR_CLIENT_NET;
	
	@JsonProperty("DBL_SELLING_CUR_CLIENT_NET") 
	private Double DBL_SELLING_CUR_CLIENT_NET;
	
	@JsonProperty("DBL_PURCHASE_CUR_INPUT_VAT") 
	private Double DBL_PURCHASE_CUR_INPUT_VAT;
	
	@JsonProperty("DBL_BASE_CUR_INPUT_VAT") 
	private Double DBL_BASE_CUR_INPUT_VAT;
	
	@JsonProperty("DBL_SELLING_CUR_INPUT_VAT") 
	private Double DBL_SELLING_CUR_INPUT_VAT;
	
	@JsonProperty("DBL_PURCHASE_CUR_OUTPUT_VAT") 
	private Double DBL_PURCHASE_CUR_OUTPUT_VAT;
	
	@JsonProperty("DBL_BASE_CUR_OUTPUT_VAT") 
	private Double DBL_BASE_CUR_OUTPUT_VAT;
	
	@JsonProperty("DBL_SELLING_CUR_OUTPUT_VAT") 
	private Double DBL_SELLING_CUR_OUTPUT_VAT;
	

	public String getSTR_TYPE() {
		return STR_TYPE;
	}

	public void setSTR_TYPE(String sTR_TYPE) {
		STR_TYPE = sTR_TYPE;
	}

	public String getSTR_XO_NUMBER() {
		return STR_XO_NUMBER;
	}

	public void setSTR_XO_NUMBER(String sTR_XO_NUMBER) {
		STR_XO_NUMBER = sTR_XO_NUMBER;
	}

	public String getSTR_TICKET_NO() {
		return STR_TICKET_NO;
	}

	public void setSTR_TICKET_NO(String sTR_TICKET_NO) {
		STR_TICKET_NO = sTR_TICKET_NO;
	}

	public String getSTR_AIRLINE_CHARACTER_CODE() {
		return STR_AIRLINE_CHARACTER_CODE;
	}

	public void setSTR_AIRLINE_CHARACTER_CODE(String sTR_AIRLINE_CHARACTER_CODE) {
		STR_AIRLINE_CHARACTER_CODE = sTR_AIRLINE_CHARACTER_CODE;
	}

	public String getSTR_AIRLINE_NUMERIC_CODE() {
		return STR_AIRLINE_NUMERIC_CODE;
	}

	public void setSTR_AIRLINE_NUMERIC_CODE(String sTR_AIRLINE_NUMERIC_CODE) {
		STR_AIRLINE_NUMERIC_CODE = sTR_AIRLINE_NUMERIC_CODE;
	}

	public String getSTR_AIRLINE_NAME() {
		return STR_AIRLINE_NAME;
	}

	public void setSTR_AIRLINE_NAME(String sTR_AIRLINE_NAME) {
		STR_AIRLINE_NAME = sTR_AIRLINE_NAME;
	}

	public String getSTR_SUPPLIER_CODE() {
		return STR_SUPPLIER_CODE;
	}

	public void setSTR_SUPPLIER_CODE(String sTR_SUPPLIER_CODE) {
		STR_SUPPLIER_CODE = sTR_SUPPLIER_CODE;
	}

	public String getSTR_CORP_CREDIT_CARD_ACCOUNT_CODE() {
		return STR_CORP_CREDIT_CARD_ACCOUNT_CODE;
	}

	public void setSTR_CORP_CREDIT_CARD_ACCOUNT_CODE(String sTR_CORP_CREDIT_CARD_ACCOUNT_CODE) {
		STR_CORP_CREDIT_CARD_ACCOUNT_CODE = sTR_CORP_CREDIT_CARD_ACCOUNT_CODE;
	}

	public String getSTR_CUSTOMER_CORP_CREDIT_CARD_ACCOUNT_CODE() {
		return STR_CUSTOMER_CORP_CREDIT_CARD_ACCOUNT_CODE;
	}

	public void setSTR_CUSTOMER_CORP_CREDIT_CARD_ACCOUNT_CODE(String sTR_CUSTOMER_CORP_CREDIT_CARD_ACCOUNT_CODE) {
		STR_CUSTOMER_CORP_CREDIT_CARD_ACCOUNT_CODE = sTR_CUSTOMER_CORP_CREDIT_CARD_ACCOUNT_CODE;
	}

	public String getSTR_TICKET_ISSUE_DATE() {
		return STR_TICKET_ISSUE_DATE;
	}

	public void setSTR_TICKET_ISSUE_DATE(String sTR_TICKET_ISSUE_DATE) {
		STR_TICKET_ISSUE_DATE = sTR_TICKET_ISSUE_DATE;
	}

	public String getSTR_REPORTING_DATE() {
		return STR_REPORTING_DATE;
	}

	public void setSTR_REPORTING_DATE(String sTR_REPORTING_DATE) {
		STR_REPORTING_DATE = sTR_REPORTING_DATE;
	}

	public String getSTR_TICKET_TYPE() {
		return STR_TICKET_TYPE;
	}

	public void setSTR_TICKET_TYPE(String sTR_TICKET_TYPE) {
		STR_TICKET_TYPE = sTR_TICKET_TYPE;
	}

	public String getSTR_TRAVELER_ID() {
		return STR_TRAVELER_ID;
	}

	public void setSTR_TRAVELER_ID(String sTR_TRAVELER_ID) {
		STR_TRAVELER_ID = sTR_TRAVELER_ID;
	}

	public String getSTR_PAX_NAME() {
		return STR_PAX_NAME;
	}

	public void setSTR_PAX_NAME(String sTR_PAX_NAME) {
		STR_PAX_NAME = sTR_PAX_NAME;
	}

	public String getSTR_ADDITIONAL_PAX() {
		return STR_ADDITIONAL_PAX;
	}

	public void setSTR_ADDITIONAL_PAX(String sTR_ADDITIONAL_PAX) {
		STR_ADDITIONAL_PAX = sTR_ADDITIONAL_PAX;
	}

	public String getSTR_SECTOR() {
		return STR_SECTOR;
	}

	public void setSTR_SECTOR(String sTR_SECTOR) {
		STR_SECTOR = sTR_SECTOR;
	}

	public String getSTR_REGION_CODE() {
		return STR_REGION_CODE;
	}

	public void setSTR_REGION_CODE(String sTR_REGION_CODE) {
		STR_REGION_CODE = sTR_REGION_CODE;
	}

	public String getSTR_LPO_NO() {
		return STR_LPO_NO;
	}

	public void setSTR_LPO_NO(String sTR_LPO_NO) {
		STR_LPO_NO = sTR_LPO_NO;
	}

	public String getSTR_CUSTOMER_REF_NO() {
		return STR_CUSTOMER_REF_NO;
	}

	public void setSTR_CUSTOMER_REF_NO(String sTR_CUSTOMER_REF_NO) {
		STR_CUSTOMER_REF_NO = sTR_CUSTOMER_REF_NO;
	}

	public String getSTR_CUSTOMER_EMP_NO() {
		return STR_CUSTOMER_EMP_NO;
	}

	public void setSTR_CUSTOMER_EMP_NO(String sTR_CUSTOMER_EMP_NO) {
		STR_CUSTOMER_EMP_NO = sTR_CUSTOMER_EMP_NO;
	}

	public String getSTR_BOOKING_STAFF_CODE() {
		return STR_BOOKING_STAFF_CODE;
	}

	public void setSTR_BOOKING_STAFF_CODE(String sTR_BOOKING_STAFF_CODE) {
		STR_BOOKING_STAFF_CODE = sTR_BOOKING_STAFF_CODE;
	}

	public String getSTR_BOOKING_STAFF_CHARACTER_CODE() {
		return STR_BOOKING_STAFF_CHARACTER_CODE;
	}

	public void setSTR_BOOKING_STAFF_CHARACTER_CODE(String sTR_BOOKING_STAFF_CHARACTER_CODE) {
		STR_BOOKING_STAFF_CHARACTER_CODE = sTR_BOOKING_STAFF_CHARACTER_CODE;
	}

	public String getSTR_BOOKING_STAFF_EMAIL_ID() {
		return STR_BOOKING_STAFF_EMAIL_ID;
	}

	public void setSTR_BOOKING_STAFF_EMAIL_ID(String sTR_BOOKING_STAFF_EMAIL_ID) {
		STR_BOOKING_STAFF_EMAIL_ID = sTR_BOOKING_STAFF_EMAIL_ID;
	}

	public String getSTR_TICKETING_STAFF_CODE() {
		return STR_TICKETING_STAFF_CODE;
	}

	public void setSTR_TICKETING_STAFF_CODE(String sTR_TICKETING_STAFF_CODE) {
		STR_TICKETING_STAFF_CODE = sTR_TICKETING_STAFF_CODE;
	}

	public String getSTR_TICKETING_STAFF_CHARACTER_CODE() {
		return STR_TICKETING_STAFF_CHARACTER_CODE;
	}

	public void setSTR_TICKETING_STAFF_CHARACTER_CODE(String sTR_TICKETING_STAFF_CHARACTER_CODE) {
		STR_TICKETING_STAFF_CHARACTER_CODE = sTR_TICKETING_STAFF_CHARACTER_CODE;
	}

	public String getSTR_TICKETING_STAFF_EMAIL_ID() {
		return STR_TICKETING_STAFF_EMAIL_ID;
	}

	public void setSTR_TICKETING_STAFF_EMAIL_ID(String sTR_TICKETING_STAFF_EMAIL_ID) {
		STR_TICKETING_STAFF_EMAIL_ID = sTR_TICKETING_STAFF_EMAIL_ID;
	}

	public String getSTR_BOOKING_AGENCY_IATA_NO() {
		return STR_BOOKING_AGENCY_IATA_NO;
	}

	public void setSTR_BOOKING_AGENCY_IATA_NO(String sTR_BOOKING_AGENCY_IATA_NO) {
		STR_BOOKING_AGENCY_IATA_NO = sTR_BOOKING_AGENCY_IATA_NO;
	}

	public String getSTR_TICKETING_AGENCY_IATA_NO() {
		return STR_TICKETING_AGENCY_IATA_NO;
	}

	public void setSTR_TICKETING_AGENCY_IATA_NO(String sTR_TICKETING_AGENCY_IATA_NO) {
		STR_TICKETING_AGENCY_IATA_NO = sTR_TICKETING_AGENCY_IATA_NO;
	}

	public String getSTR_BOOKING_AGENCY_OFFICE_ID() {
		return STR_BOOKING_AGENCY_OFFICE_ID;
	}

	public void setSTR_BOOKING_AGENCY_OFFICE_ID(String sTR_BOOKING_AGENCY_OFFICE_ID) {
		STR_BOOKING_AGENCY_OFFICE_ID = sTR_BOOKING_AGENCY_OFFICE_ID;
	}

	public String getSTR_TICKETING_AGENCY_OFFICE_ID() {
		return STR_TICKETING_AGENCY_OFFICE_ID;
	}

	public void setSTR_TICKETING_AGENCY_OFFICE_ID(String sTR_TICKETING_AGENCY_OFFICE_ID) {
		STR_TICKETING_AGENCY_OFFICE_ID = sTR_TICKETING_AGENCY_OFFICE_ID;
	}

	public String getSTR_PNR_FIRST_OWNER_OFFICE_ID() {
		return STR_PNR_FIRST_OWNER_OFFICE_ID;
	}

	public void setSTR_PNR_FIRST_OWNER_OFFICE_ID(String sTR_PNR_FIRST_OWNER_OFFICE_ID) {
		STR_PNR_FIRST_OWNER_OFFICE_ID = sTR_PNR_FIRST_OWNER_OFFICE_ID;
	}

	public String getSTR_PNR_CURRENT_OWNER_OFFICE_ID() {
		return STR_PNR_CURRENT_OWNER_OFFICE_ID;
	}

	public void setSTR_PNR_CURRENT_OWNER_OFFICE_ID(String sTR_PNR_CURRENT_OWNER_OFFICE_ID) {
		STR_PNR_CURRENT_OWNER_OFFICE_ID = sTR_PNR_CURRENT_OWNER_OFFICE_ID;
	}

	public String getSTR_GDS() {
		return STR_GDS;
	}

	public void setSTR_GDS(String sTR_GDS) {
		STR_GDS = sTR_GDS;
	}

	public String getSTR_TOUR_CODE() {
		return STR_TOUR_CODE;
	}

	public void setSTR_TOUR_CODE(String sTR_TOUR_CODE) {
		STR_TOUR_CODE = sTR_TOUR_CODE;
	}

	public String getSTR_FARE_BASIS() {
		return STR_FARE_BASIS;
	}

	public void setSTR_FARE_BASIS(String sTR_FARE_BASIS) {
		STR_FARE_BASIS = sTR_FARE_BASIS;
	}

	public String getSTR_PNR_NO() {
		return STR_PNR_NO;
	}

	public void setSTR_PNR_NO(String sTR_PNR_NO) {
		STR_PNR_NO = sTR_PNR_NO;
	}

	public String getSTR_AIRLINE_PNR() {
		return STR_AIRLINE_PNR;
	}

	public void setSTR_AIRLINE_PNR(String sTR_AIRLINE_PNR) {
		STR_AIRLINE_PNR = sTR_AIRLINE_PNR;
	}

	public Integer getINT_NO_OF_PAX() {
		return INT_NO_OF_PAX;
	}

	public void setINT_NO_OF_PAX(Integer iNT_NO_OF_PAX) {
		INT_NO_OF_PAX = iNT_NO_OF_PAX;
	}

	public String getSTR_PAX_TYPE() {
		return STR_PAX_TYPE;
	}

	public void setSTR_PAX_TYPE(String sTR_PAX_TYPE) {
		STR_PAX_TYPE = sTR_PAX_TYPE;
	}

	public String getSTR_LAST_CONJ_TICKET() {
		return STR_LAST_CONJ_TICKET;
	}

	public void setSTR_LAST_CONJ_TICKET(String sTR_LAST_CONJ_TICKET) {
		STR_LAST_CONJ_TICKET = sTR_LAST_CONJ_TICKET;
	}

	public String getSTR_ORIGINAL_ISSUE() {
		return STR_ORIGINAL_ISSUE;
	}

	public void setSTR_ORIGINAL_ISSUE(String sTR_ORIGINAL_ISSUE) {
		STR_ORIGINAL_ISSUE = sTR_ORIGINAL_ISSUE;
	}

	public String getSTR_TRAVEL_DATE() {
		return STR_TRAVEL_DATE;
	}

	public void setSTR_TRAVEL_DATE(String sTR_TRAVEL_DATE) {
		STR_TRAVEL_DATE = sTR_TRAVEL_DATE;
	}

	public String getSTR_RETURN_DATE() {
		return STR_RETURN_DATE;
	}

	public void setSTR_RETURN_DATE(String sTR_RETURN_DATE) {
		STR_RETURN_DATE = sTR_RETURN_DATE;
	}

	public String getSTR_TICKET_REMARK() {
		return STR_TICKET_REMARK;
	}

	public void setSTR_TICKET_REMARK(String sTR_TICKET_REMARK) {
		STR_TICKET_REMARK = sTR_TICKET_REMARK;
	}

	public String getSTR_PRODUCT() {
		return STR_PRODUCT;
	}

	public void setSTR_PRODUCT(String sTR_PRODUCT) {
		STR_PRODUCT = sTR_PRODUCT;
	}

	public Double getDBL_PURCHASE_ROE() {
		return DBL_PURCHASE_ROE;
	}

	public void setDBL_PURCHASE_ROE(Double dBL_PURCHASE_ROE) {
		DBL_PURCHASE_ROE = dBL_PURCHASE_ROE;
	}

	public Double getDBL_PURCHASE_CUR_PUBLISHED_FARE() {
		return DBL_PURCHASE_CUR_PUBLISHED_FARE;
	}

	public void setDBL_PURCHASE_CUR_PUBLISHED_FARE(Double dBL_PURCHASE_CUR_PUBLISHED_FARE) {
		DBL_PURCHASE_CUR_PUBLISHED_FARE = dBL_PURCHASE_CUR_PUBLISHED_FARE;
	}

	public Double getDBL_BASE_CUR_PUBLISHED_FARE() {
		return DBL_BASE_CUR_PUBLISHED_FARE;
	}

	public void setDBL_BASE_CUR_PUBLISHED_FARE(Double dBL_BASE_CUR_PUBLISHED_FARE) {
		DBL_BASE_CUR_PUBLISHED_FARE = dBL_BASE_CUR_PUBLISHED_FARE;
	}

	public Double getDBL_SELLING_CUR_PUBLISHED_FARE() {
		return DBL_SELLING_CUR_PUBLISHED_FARE;
	}

	public void setDBL_SELLING_CUR_PUBLISHED_FARE(Double dBL_SELLING_CUR_PUBLISHED_FARE) {
		DBL_SELLING_CUR_PUBLISHED_FARE = dBL_SELLING_CUR_PUBLISHED_FARE;
	}

	public Double getDBL_PURCHASE_CUR_TOTAL_MARKET_FARE() {
		return DBL_PURCHASE_CUR_TOTAL_MARKET_FARE;
	}

	public void setDBL_PURCHASE_CUR_TOTAL_MARKET_FARE(Double dBL_PURCHASE_CUR_TOTAL_MARKET_FARE) {
		DBL_PURCHASE_CUR_TOTAL_MARKET_FARE = dBL_PURCHASE_CUR_TOTAL_MARKET_FARE;
	}

	public Double getDBL_BASE_CUR_TOTAL_MARKET_FARE() {
		return DBL_BASE_CUR_TOTAL_MARKET_FARE;
	}

	public void setDBL_BASE_CUR_TOTAL_MARKET_FARE(Double dBL_BASE_CUR_TOTAL_MARKET_FARE) {
		DBL_BASE_CUR_TOTAL_MARKET_FARE = dBL_BASE_CUR_TOTAL_MARKET_FARE;
	}

	public Double getDBL_SELLING_CUR_TOTAL_MARKET_FARE() {
		return DBL_SELLING_CUR_TOTAL_MARKET_FARE;
	}

	public void setDBL_SELLING_CUR_TOTAL_MARKET_FARE(Double dBL_SELLING_CUR_TOTAL_MARKET_FARE) {
		DBL_SELLING_CUR_TOTAL_MARKET_FARE = dBL_SELLING_CUR_TOTAL_MARKET_FARE;
	}

	public Double getDBL_PURCHASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD() {
		return DBL_PURCHASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD;
	}

	public void setDBL_PURCHASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD(Double dBL_PURCHASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD) {
		DBL_PURCHASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD = dBL_PURCHASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD;
	}

	public Double getDBL_BASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD() {
		return DBL_BASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD;
	}

	public void setDBL_BASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD(Double dBL_BASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD) {
		DBL_BASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD = dBL_BASE_CUR_TOTAL_MARKET_FARE_CREDIT_CARD;
	}

	public Double getDBL_SELLING_CUR_TOTAL_MARKET_FARE_CREDIT_CARD() {
		return DBL_SELLING_CUR_TOTAL_MARKET_FARE_CREDIT_CARD;
	}

	public void setDBL_SELLING_CUR_TOTAL_MARKET_FARE_CREDIT_CARD(Double dBL_SELLING_CUR_TOTAL_MARKET_FARE_CREDIT_CARD) {
		DBL_SELLING_CUR_TOTAL_MARKET_FARE_CREDIT_CARD = dBL_SELLING_CUR_TOTAL_MARKET_FARE_CREDIT_CARD;
	}

	public String getSTR_TAX_DETAILS() {
		return STR_TAX_DETAILS;
	}

	public void setSTR_TAX_DETAILS(String sTR_TAX_DETAILS) {
		STR_TAX_DETAILS = sTR_TAX_DETAILS;
	}

	public Double getDBL_PURCHASE_CUR_TOTAL_TAX() {
		return DBL_PURCHASE_CUR_TOTAL_TAX;
	}

	public void setDBL_PURCHASE_CUR_TOTAL_TAX(Double dBL_PURCHASE_CUR_TOTAL_TAX) {
		DBL_PURCHASE_CUR_TOTAL_TAX = dBL_PURCHASE_CUR_TOTAL_TAX;
	}

	public Double getDBL_BASE_CUR_TOTAL_TAX() {
		return DBL_BASE_CUR_TOTAL_TAX;
	}

	public void setDBL_BASE_CUR_TOTAL_TAX(Double dBL_BASE_CUR_TOTAL_TAX) {
		DBL_BASE_CUR_TOTAL_TAX = dBL_BASE_CUR_TOTAL_TAX;
	}

	public Double getDBL_SELLING_CUR_TOTAL_TAX() {
		return DBL_SELLING_CUR_TOTAL_TAX;
	}

	public void setDBL_SELLING_CUR_TOTAL_TAX(Double dBL_SELLING_CUR_TOTAL_TAX) {
		DBL_SELLING_CUR_TOTAL_TAX = dBL_SELLING_CUR_TOTAL_TAX;
	}

	public Double getDBL_PURCHASE_CUR_TOTAL_TAX_CREDIT_CARD() {
		return DBL_PURCHASE_CUR_TOTAL_TAX_CREDIT_CARD;
	}

	public void setDBL_PURCHASE_CUR_TOTAL_TAX_CREDIT_CARD(Double dBL_PURCHASE_CUR_TOTAL_TAX_CREDIT_CARD) {
		DBL_PURCHASE_CUR_TOTAL_TAX_CREDIT_CARD = dBL_PURCHASE_CUR_TOTAL_TAX_CREDIT_CARD;
	}

	public Double getDBL_BASE_CUR_TOTAL_TAX_CREDIT_CARD() {
		return DBL_BASE_CUR_TOTAL_TAX_CREDIT_CARD;
	}

	public void setDBL_BASE_CUR_TOTAL_TAX_CREDIT_CARD(Double dBL_BASE_CUR_TOTAL_TAX_CREDIT_CARD) {
		DBL_BASE_CUR_TOTAL_TAX_CREDIT_CARD = dBL_BASE_CUR_TOTAL_TAX_CREDIT_CARD;
	}

	public Double getDBL_SELLING_CUR_TOTAL_TAX_CREDIT_CARD() {
		return DBL_SELLING_CUR_TOTAL_TAX_CREDIT_CARD;
	}

	public void setDBL_SELLING_CUR_TOTAL_TAX_CREDIT_CARD(Double dBL_SELLING_CUR_TOTAL_TAX_CREDIT_CARD) {
		DBL_SELLING_CUR_TOTAL_TAX_CREDIT_CARD = dBL_SELLING_CUR_TOTAL_TAX_CREDIT_CARD;
	}

	public Double getDBL_PURCHASE_CUR_STD_COMMISION() {
		return DBL_PURCHASE_CUR_STD_COMMISION;
	}

	public void setDBL_PURCHASE_CUR_STD_COMMISION(Double dBL_PURCHASE_CUR_STD_COMMISION) {
		DBL_PURCHASE_CUR_STD_COMMISION = dBL_PURCHASE_CUR_STD_COMMISION;
	}

	public Double getDBL_BASE_CUR_STD_COMMISION() {
		return DBL_BASE_CUR_STD_COMMISION;
	}

	public void setDBL_BASE_CUR_STD_COMMISION(Double dBL_BASE_CUR_STD_COMMISION) {
		DBL_BASE_CUR_STD_COMMISION = dBL_BASE_CUR_STD_COMMISION;
	}

	public Double getDBL_SELLING_CUR_STD_COMMISION() {
		return DBL_SELLING_CUR_STD_COMMISION;
	}

	public void setDBL_SELLING_CUR_STD_COMMISION(Double dBL_SELLING_CUR_STD_COMMISION) {
		DBL_SELLING_CUR_STD_COMMISION = dBL_SELLING_CUR_STD_COMMISION;
	}

	public Double getDBL_PURCHASE_CUR_SUPPLIER_FEE() {
		return DBL_PURCHASE_CUR_SUPPLIER_FEE;
	}

	public void setDBL_PURCHASE_CUR_SUPPLIER_FEE(Double dBL_PURCHASE_CUR_SUPPLIER_FEE) {
		DBL_PURCHASE_CUR_SUPPLIER_FEE = dBL_PURCHASE_CUR_SUPPLIER_FEE;
	}

	public Double getDBL_BASE_CUR_SUPPLIER_FEE() {
		return DBL_BASE_CUR_SUPPLIER_FEE;
	}

	public void setDBL_BASE_CUR_SUPPLIER_FEE(Double dBL_BASE_CUR_SUPPLIER_FEE) {
		DBL_BASE_CUR_SUPPLIER_FEE = dBL_BASE_CUR_SUPPLIER_FEE;
	}

	public Double getDBL_SELLING_CUR_SUPPLIER_FEE() {
		return DBL_SELLING_CUR_SUPPLIER_FEE;
	}

	public void setDBL_SELLING_CUR_SUPPLIER_FEE(Double dBL_SELLING_CUR_SUPPLIER_FEE) {
		DBL_SELLING_CUR_SUPPLIER_FEE = dBL_SELLING_CUR_SUPPLIER_FEE;
	}

	public Double getDBL_PURCHASE_CUR_SUPPLIER_AMOUNT() {
		return DBL_PURCHASE_CUR_SUPPLIER_AMOUNT;
	}

	public void setDBL_PURCHASE_CUR_SUPPLIER_AMOUNT(Double dBL_PURCHASE_CUR_SUPPLIER_AMOUNT) {
		DBL_PURCHASE_CUR_SUPPLIER_AMOUNT = dBL_PURCHASE_CUR_SUPPLIER_AMOUNT;
	}

	public Double getDBL_BASE_CUR_SUPPLIER_AMOUNT() {
		return DBL_BASE_CUR_SUPPLIER_AMOUNT;
	}

	public void setDBL_BASE_CUR_SUPPLIER_AMOUNT(Double dBL_BASE_CUR_SUPPLIER_AMOUNT) {
		DBL_BASE_CUR_SUPPLIER_AMOUNT = dBL_BASE_CUR_SUPPLIER_AMOUNT;
	}

	public Double getDBL_SELLING_CUR_SUPPLIER_AMOUNT() {
		return DBL_SELLING_CUR_SUPPLIER_AMOUNT;
	}

	public void setDBL_SELLING_CUR_SUPPLIER_AMOUNT(Double dBL_SELLING_CUR_SUPPLIER_AMOUNT) {
		DBL_SELLING_CUR_SUPPLIER_AMOUNT = dBL_SELLING_CUR_SUPPLIER_AMOUNT;
	}

	public Double getDBL_PURCHASE_CUR_SERVICE_FEE() {
		return DBL_PURCHASE_CUR_SERVICE_FEE;
	}

	public void setDBL_PURCHASE_CUR_SERVICE_FEE(Double dBL_PURCHASE_CUR_SERVICE_FEE) {
		DBL_PURCHASE_CUR_SERVICE_FEE = dBL_PURCHASE_CUR_SERVICE_FEE;
	}

	public Double getDBL_BASE_CUR_SERVICE_FEE() {
		return DBL_BASE_CUR_SERVICE_FEE;
	}

	public void setDBL_BASE_CUR_SERVICE_FEE(Double dBL_BASE_CUR_SERVICE_FEE) {
		DBL_BASE_CUR_SERVICE_FEE = dBL_BASE_CUR_SERVICE_FEE;
	}

	public Double getDBL_SELLING_CUR_SERVICE_FEE() {
		return DBL_SELLING_CUR_SERVICE_FEE;
	}

	public void setDBL_SELLING_CUR_SERVICE_FEE(Double dBL_SELLING_CUR_SERVICE_FEE) {
		DBL_SELLING_CUR_SERVICE_FEE = dBL_SELLING_CUR_SERVICE_FEE;
	}

	public Double getDBL_PURCHASE_CUR_EXTRA_EARNING() {
		return DBL_PURCHASE_CUR_EXTRA_EARNING;
	}

	public void setDBL_PURCHASE_CUR_EXTRA_EARNING(Double dBL_PURCHASE_CUR_EXTRA_EARNING) {
		DBL_PURCHASE_CUR_EXTRA_EARNING = dBL_PURCHASE_CUR_EXTRA_EARNING;
	}

	public Double getDBL_BASE_CUR_EXTRA_EARNING() {
		return DBL_BASE_CUR_EXTRA_EARNING;
	}

	public void setDBL_BASE_CUR_EXTRA_EARNING(Double dBL_BASE_CUR_EXTRA_EARNING) {
		DBL_BASE_CUR_EXTRA_EARNING = dBL_BASE_CUR_EXTRA_EARNING;
	}

	public Double getDBL_SELLING_CUR_EXTRA_EARNING() {
		return DBL_SELLING_CUR_EXTRA_EARNING;
	}

	public void setDBL_SELLING_CUR_EXTRA_EARNING(Double dBL_SELLING_CUR_EXTRA_EARNING) {
		DBL_SELLING_CUR_EXTRA_EARNING = dBL_SELLING_CUR_EXTRA_EARNING;
	}

	public Double getDBL_PURCHASE_CUR_PAYBACK_AMOUNT() {
		return DBL_PURCHASE_CUR_PAYBACK_AMOUNT;
	}

	public void setDBL_PURCHASE_CUR_PAYBACK_AMOUNT(Double dBL_PURCHASE_CUR_PAYBACK_AMOUNT) {
		DBL_PURCHASE_CUR_PAYBACK_AMOUNT = dBL_PURCHASE_CUR_PAYBACK_AMOUNT;
	}

	public Double getDBL_BASE_CUR_PAYBACK_AMOUNT() {
		return DBL_BASE_CUR_PAYBACK_AMOUNT;
	}

	public void setDBL_BASE_CUR_PAYBACK_AMOUNT(Double dBL_BASE_CUR_PAYBACK_AMOUNT) {
		DBL_BASE_CUR_PAYBACK_AMOUNT = dBL_BASE_CUR_PAYBACK_AMOUNT;
	}

	public Double getDBL_SELLING_CUR_PAYBACK_AMOUNT() {
		return DBL_SELLING_CUR_PAYBACK_AMOUNT;
	}

	public void setDBL_SELLING_CUR_PAYBACK_AMOUNT(Double dBL_SELLING_CUR_PAYBACK_AMOUNT) {
		DBL_SELLING_CUR_PAYBACK_AMOUNT = dBL_SELLING_CUR_PAYBACK_AMOUNT;
	}

	public String getSTR_PAYBACK_ACCOUNT_CODE() {
		return STR_PAYBACK_ACCOUNT_CODE;
	}

	public void setSTR_PAYBACK_ACCOUNT_CODE(String sTR_PAYBACK_ACCOUNT_CODE) {
		STR_PAYBACK_ACCOUNT_CODE = sTR_PAYBACK_ACCOUNT_CODE;
	}

	public Double getDBL_PURCHASE_CUR_CREDIT_CARD_CHARGES() {
		return DBL_PURCHASE_CUR_CREDIT_CARD_CHARGES;
	}

	public void setDBL_PURCHASE_CUR_CREDIT_CARD_CHARGES(Double dBL_PURCHASE_CUR_CREDIT_CARD_CHARGES) {
		DBL_PURCHASE_CUR_CREDIT_CARD_CHARGES = dBL_PURCHASE_CUR_CREDIT_CARD_CHARGES;
	}

	public Double getDBL_BASE_CUR_CREDIT_CARD_CHARGES() {
		return DBL_BASE_CUR_CREDIT_CARD_CHARGES;
	}

	public void setDBL_BASE_CUR_CREDIT_CARD_CHARGES(Double dBL_BASE_CUR_CREDIT_CARD_CHARGES) {
		DBL_BASE_CUR_CREDIT_CARD_CHARGES = dBL_BASE_CUR_CREDIT_CARD_CHARGES;
	}

	public Double getDBL_SELLING_CUR_CREDIT_CARD_CHARGES() {
		return DBL_SELLING_CUR_CREDIT_CARD_CHARGES;
	}

	public void setDBL_SELLING_CUR_CREDIT_CARD_CHARGES(Double dBL_SELLING_CUR_CREDIT_CARD_CHARGES) {
		DBL_SELLING_CUR_CREDIT_CARD_CHARGES = dBL_SELLING_CUR_CREDIT_CARD_CHARGES;
	}

	public Double getDBL_PURCHASE_CUR_DISCOUNT() {
		return DBL_PURCHASE_CUR_DISCOUNT;
	}

	public void setDBL_PURCHASE_CUR_DISCOUNT(Double dBL_PURCHASE_CUR_DISCOUNT) {
		DBL_PURCHASE_CUR_DISCOUNT = dBL_PURCHASE_CUR_DISCOUNT;
	}

	public Double getDBL_BASE_CUR_DISCOUNT() {
		return DBL_BASE_CUR_DISCOUNT;
	}

	public void setDBL_BASE_CUR_DISCOUNT(Double dBL_BASE_CUR_DISCOUNT) {
		DBL_BASE_CUR_DISCOUNT = dBL_BASE_CUR_DISCOUNT;
	}

	public Double getDBL_SELLING_CUR_DISCOUNT() {
		return DBL_SELLING_CUR_DISCOUNT;
	}

	public void setDBL_SELLING_CUR_DISCOUNT(Double dBL_SELLING_CUR_DISCOUNT) {
		DBL_SELLING_CUR_DISCOUNT = dBL_SELLING_CUR_DISCOUNT;
	}

	public Double getDBL_PURCHASE_CUR_PRICE() {
		return DBL_PURCHASE_CUR_PRICE;
	}

	public void setDBL_PURCHASE_CUR_PRICE(Double dBL_PURCHASE_CUR_PRICE) {
		DBL_PURCHASE_CUR_PRICE = dBL_PURCHASE_CUR_PRICE;
	}

	public Double getDBL_BASE_CUR_PRICE() {
		return DBL_BASE_CUR_PRICE;
	}

	public void setDBL_BASE_CUR_PRICE(Double dBL_BASE_CUR_PRICE) {
		DBL_BASE_CUR_PRICE = dBL_BASE_CUR_PRICE;
	}

	public Double getDBL_SELLING_CUR_PRICE() {
		return DBL_SELLING_CUR_PRICE;
	}

	public void setDBL_SELLING_CUR_PRICE(Double dBL_SELLING_CUR_PRICE) {
		DBL_SELLING_CUR_PRICE = dBL_SELLING_CUR_PRICE;
	}

	public String getSTR_AIRLINE_REF_NO() {
		return STR_AIRLINE_REF_NO;
	}

	public void setSTR_AIRLINE_REF_NO(String sTR_AIRLINE_REF_NO) {
		STR_AIRLINE_REF_NO = sTR_AIRLINE_REF_NO;
	}

	public String getSTR_REFUND_DATE() {
		return STR_REFUND_DATE;
	}

	public void setSTR_REFUND_DATE(String sTR_REFUND_DATE) {
		STR_REFUND_DATE = sTR_REFUND_DATE;
	}

	public String getSTR_REFUND_STAFF_CODE() {
		return STR_REFUND_STAFF_CODE;
	}

	public void setSTR_REFUND_STAFF_CODE(String sTR_REFUND_STAFF_CODE) {
		STR_REFUND_STAFF_CODE = sTR_REFUND_STAFF_CODE;
	}

	public String getSTR_REFUND_STAFF_CHARACTER_CODE() {
		return STR_REFUND_STAFF_CHARACTER_CODE;
	}

	public void setSTR_REFUND_STAFF_CHARACTER_CODE(String sTR_REFUND_STAFF_CHARACTER_CODE) {
		STR_REFUND_STAFF_CHARACTER_CODE = sTR_REFUND_STAFF_CHARACTER_CODE;
	}

	public String getSTR_REFUND_STAFF_EMAIL_ID() {
		return STR_REFUND_STAFF_EMAIL_ID;
	}

	public void setSTR_REFUND_STAFF_EMAIL_ID(String sTR_REFUND_STAFF_EMAIL_ID) {
		STR_REFUND_STAFF_EMAIL_ID = sTR_REFUND_STAFF_EMAIL_ID;
	}

	public String getSTR_REFUND_STATUS() {
		return STR_REFUND_STATUS;
	}

	public void setSTR_REFUND_STATUS(String sTR_REFUND_STATUS) {
		STR_REFUND_STATUS = sTR_REFUND_STATUS;
	}

	public Double getDBL_PURCHASE_CUR_AIRLINE_CHARGE() {
		return DBL_PURCHASE_CUR_AIRLINE_CHARGE;
	}

	public void setDBL_PURCHASE_CUR_AIRLINE_CHARGE(Double dBL_PURCHASE_CUR_AIRLINE_CHARGE) {
		DBL_PURCHASE_CUR_AIRLINE_CHARGE = dBL_PURCHASE_CUR_AIRLINE_CHARGE;
	}

	public Double getDBL_BASE_CUR_AIRLINE_CHARGE() {
		return DBL_BASE_CUR_AIRLINE_CHARGE;
	}

	public void setDBL_BASE_CUR_AIRLINE_CHARGE(Double dBL_BASE_CUR_AIRLINE_CHARGE) {
		DBL_BASE_CUR_AIRLINE_CHARGE = dBL_BASE_CUR_AIRLINE_CHARGE;
	}

	public Double getDBL_SELLING_CUR_AIRLINE_CHARGE() {
		return DBL_SELLING_CUR_AIRLINE_CHARGE;
	}

	public void setDBL_SELLING_CUR_AIRLINE_CHARGE(Double dBL_SELLING_CUR_AIRLINE_CHARGE) {
		DBL_SELLING_CUR_AIRLINE_CHARGE = dBL_SELLING_CUR_AIRLINE_CHARGE;
	}

	public Double getDBL_PURCHASE_CUR_SUPPLIER_NET() {
		return DBL_PURCHASE_CUR_SUPPLIER_NET;
	}

	public void setDBL_PURCHASE_CUR_SUPPLIER_NET(Double dBL_PURCHASE_CUR_SUPPLIER_NET) {
		DBL_PURCHASE_CUR_SUPPLIER_NET = dBL_PURCHASE_CUR_SUPPLIER_NET;
	}

	public Double getDBL_BASE_CUR_SUPPLIER_NET() {
		return DBL_BASE_CUR_SUPPLIER_NET;
	}

	public void setDBL_BASE_CUR_SUPPLIER_NET(Double dBL_BASE_CUR_SUPPLIER_NET) {
		DBL_BASE_CUR_SUPPLIER_NET = dBL_BASE_CUR_SUPPLIER_NET;
	}

	public Double getDBL_SELLING_CUR_SUPPLIER_NET() {
		return DBL_SELLING_CUR_SUPPLIER_NET;
	}

	public void setDBL_SELLING_CUR_SUPPLIER_NET(Double dBL_SELLING_CUR_SUPPLIER_NET) {
		DBL_SELLING_CUR_SUPPLIER_NET = dBL_SELLING_CUR_SUPPLIER_NET;
	}

	public Double getDBL_PURCHASE_CUR_AGENCY_CHARGE() {
		return DBL_PURCHASE_CUR_AGENCY_CHARGE;
	}

	public void setDBL_PURCHASE_CUR_AGENCY_CHARGE(Double dBL_PURCHASE_CUR_AGENCY_CHARGE) {
		DBL_PURCHASE_CUR_AGENCY_CHARGE = dBL_PURCHASE_CUR_AGENCY_CHARGE;
	}

	public Double getDBL_BASE_CUR_AGENCY_CHARGE() {
		return DBL_BASE_CUR_AGENCY_CHARGE;
	}

	public void setDBL_BASE_CUR_AGENCY_CHARGE(Double dBL_BASE_CUR_AGENCY_CHARGE) {
		DBL_BASE_CUR_AGENCY_CHARGE = dBL_BASE_CUR_AGENCY_CHARGE;
	}

	public Double getDBL_SELLING_CUR_AGENCY_CHARGE() {
		return DBL_SELLING_CUR_AGENCY_CHARGE;
	}

	public void setDBL_SELLING_CUR_AGENCY_CHARGE(Double dBL_SELLING_CUR_AGENCY_CHARGE) {
		DBL_SELLING_CUR_AGENCY_CHARGE = dBL_SELLING_CUR_AGENCY_CHARGE;
	}

	public Double getDBL_PURCHASE_CUR_CLIENT_NET() {
		return DBL_PURCHASE_CUR_CLIENT_NET;
	}

	public void setDBL_PURCHASE_CUR_CLIENT_NET(Double dBL_PURCHASE_CUR_CLIENT_NET) {
		DBL_PURCHASE_CUR_CLIENT_NET = dBL_PURCHASE_CUR_CLIENT_NET;
	}

	public Double getDBL_BASE_CUR_CLIENT_NET() {
		return DBL_BASE_CUR_CLIENT_NET;
	}

	public void setDBL_BASE_CUR_CLIENT_NET(Double dBL_BASE_CUR_CLIENT_NET) {
		DBL_BASE_CUR_CLIENT_NET = dBL_BASE_CUR_CLIENT_NET;
	}

	public Double getDBL_SELLING_CUR_CLIENT_NET() {
		return DBL_SELLING_CUR_CLIENT_NET;
	}

	public void setDBL_SELLING_CUR_CLIENT_NET(Double dBL_SELLING_CUR_CLIENT_NET) {
		DBL_SELLING_CUR_CLIENT_NET = dBL_SELLING_CUR_CLIENT_NET;
	}

	public String getSTR_PURCHASE_CUR_CODE() {
		return STR_PURCHASE_CUR_CODE;
	}

	public void setSTR_PURCHASE_CUR_CODE(String sTR_PURCHASE_CUR_CODE) {
		STR_PURCHASE_CUR_CODE = sTR_PURCHASE_CUR_CODE;
	}

	public String getCHR_RETURN_CLASS() {
		return CHR_RETURN_CLASS;
	}

	public void setCHR_RETURN_CLASS(String cHR_RETURN_CLASS) {
		CHR_RETURN_CLASS = cHR_RETURN_CLASS;
	}

	public String getCHR_TRAVELER_CLASS() {
		return CHR_TRAVELER_CLASS;
	}

	public void setCHR_TRAVELER_CLASS(String cHR_TRAVELER_CLASS) {
		CHR_TRAVELER_CLASS = cHR_TRAVELER_CLASS;
	}

	public Double getDBL_PURCHASE_CUR_INPUT_VAT() {
		return DBL_PURCHASE_CUR_INPUT_VAT;
	}

	public void setDBL_PURCHASE_CUR_INPUT_VAT(Double dBL_PURCHASE_CUR_INPUT_VAT) {
		DBL_PURCHASE_CUR_INPUT_VAT = dBL_PURCHASE_CUR_INPUT_VAT;
	}

	public Double getDBL_BASE_CUR_INPUT_VAT() {
		return DBL_BASE_CUR_INPUT_VAT;
	}

	public void setDBL_BASE_CUR_INPUT_VAT(Double dBL_BASE_CUR_INPUT_VAT) {
		DBL_BASE_CUR_INPUT_VAT = dBL_BASE_CUR_INPUT_VAT;
	}

	public Double getDBL_SELLING_CUR_INPUT_VAT() {
		return DBL_SELLING_CUR_INPUT_VAT;
	}

	public void setDBL_SELLING_CUR_INPUT_VAT(Double dBL_SELLING_CUR_INPUT_VAT) {
		DBL_SELLING_CUR_INPUT_VAT = dBL_SELLING_CUR_INPUT_VAT;
	}

	public Double getDBL_PURCHASE_CUR_OUTPUT_VAT() {
		return DBL_PURCHASE_CUR_OUTPUT_VAT;
	}

	public void setDBL_PURCHASE_CUR_OUTPUT_VAT(Double dBL_PURCHASE_CUR_OUTPUT_VAT) {
		DBL_PURCHASE_CUR_OUTPUT_VAT = dBL_PURCHASE_CUR_OUTPUT_VAT;
	}

	public Double getDBL_BASE_CUR_OUTPUT_VAT() {
		return DBL_BASE_CUR_OUTPUT_VAT;
	}

	public void setDBL_BASE_CUR_OUTPUT_VAT(Double dBL_BASE_CUR_OUTPUT_VAT) {
		DBL_BASE_CUR_OUTPUT_VAT = dBL_BASE_CUR_OUTPUT_VAT;
	}

	public Double getDBL_SELLING_CUR_OUTPUT_VAT() {
		return DBL_SELLING_CUR_OUTPUT_VAT;
	}

	public void setDBL_SELLING_CUR_OUTPUT_VAT(Double dBL_SELLING_CUR_OUTPUT_VAT) {
		DBL_SELLING_CUR_OUTPUT_VAT = dBL_SELLING_CUR_OUTPUT_VAT;
	}	
	
}
